### PR TITLE
refactored popup.js

### PR DESCRIPTION
**Pull request by niksoc**
Sorry for the delay. Yes, please write the AJAX request. Also code for deleting from local storage is in this PR. (Previously the bookmark was removed only visually). Also now the bookmarks are synced with mal (if I delete a manga in mal, it will get deleted from the bookmarks).

### CODE REVIEW

**Comment by nyczbrandon** [comment]
Do you think I should differentiate between drop and delete?  I made it so that clicking drop deletes the entry from your myanimelist completely.  But drop could also be setting the manga status to dropped rather than deleting it from myanimelist.

**Comment by niksoc** [comment]
I think it should be setting the status to dropped, user can delete later from mal if he wants to, but delete is irreversible. Completed button is also supposed to change the status so the behaviour will be uniform. Adding a separate delete button would result in too many buttons, so no need for that.
edit: on second thought maybe a separate delete button will be useful too, (for eg. when a manga gets added by mistake).

**Comment by nyczbrandon** [comment]
What is eventpage.js?

**Comment by niksoc** [comment]
I added a notification that pops up whenever a new manga is added, it also has a button that says 'No, don't add this manga now' but currently that button only gives an alert. Refer [this](https://developer.chrome.com/extensions/event_pages) and [this](https://developer.chrome.com/apps/richNotifications). Notifications are not available in content.js that's why I added the eventPage.

What do you think?
edit: ooh sorry, since i used git commit -a instead of git add, the eventPage wasn't tracked by git. I've pushed again

**Comment by nyczbrandon** [comment]
I have an issue where if I read something new, the old bookmark no longer shows.  So there is only like on bookmark at a time.

**Comment by niksoc** [comment]
I'm not facing that problem actually, is your copy up to date with my repo (especially content.js)?

**Comment by nyczbrandon** [comment]
Oh yeah you're right.  I still had an old version where in sync_bookmarks it check if status = 1 || status = 3 rather than status = 1 && status = 3.

**Comment by nyczbrandon** [comment]
I decided not to add the notification in it's current form, but added everything else.

**Comment by nyczbrandon** [comment]
I'll this for a little bit in case you have anything you wanted to discuss.

**Comment by niksoc** [comment]
Should I continue work on notifications or..?

**Comment by nyczbrandon** [comment]
If you want to, but I think you should change the way it works.  Rather than add the manga then ask if they want to keep it and then dropping it.  I think it is better if you prompt the notification before adding the manga.

**Comment by niksoc** [comment]
alright, i'll open another PR for that later

**Pull request closed without merging**
