### PR TITLE
added bookmarks functionality

### PR DESCRIPTION
**Pull request by niksoc**
Now bookmarks (links to the bato.to or kissmanga page to the chapter you were on) also get saved automatically and appear in the popup. The bookmark gets updated/added whenever the mal manga list gets updated. The main function in content.js is save_bookmark. In login.js I've added the code to display the bookmark list in the popup.

### CODE REVIEW

**Comment by nyczbrandon** [comment]
Can you fix some of the indentation in your code to be a consistent with mine.  Also I think your fork was from an older version from before I added 'use strict'.  Also I noticed that on the popup.html when they are not yet logged in there is blank space to the right of the form.

**Comment by nyczbrandon** [comment]
Hi I added GPL3 License to my project, let me know if that is okay with you.

**Comment by niksoc** [comment]
That's okay. I've changed the indentation, could you check and let me know if that's what you meant? I've also fixed the extra space during login.

**Comment by nyczbrandon** [comment]
Yeah that's good, I have merged this pull request to add bookmarks.

**Pull request merged**
